# Generated by Django 3.0.5 on 2020-05-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=80)),
                ('post_code', models.CharField(max_length=6)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=20)),
                ('city', models.CharField(choices=[('WARSAW', 'Warsaw'), ('POZNAN', 'Poznan'), ('WROCLAW', 'Wroclaw'), ('CRACOW', 'Cracow')], max_length=20)),
                ('etc', models.TextField(max_length=500)),
            ],
        ),
    ]
