# Generated by Django 3.0.5 on 2020-05-16 23:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enroll_date',
            field=models.TimeField(default=datetime.datetime(2020, 5, 16, 23, 51, 0, 915884, tzinfo=utc)),
        ),
    ]
